image: Visual Studio 2019
version: '{build}'
configuration: Release

environment:
  api_key:
    secure: 7jEF+EPlBwHDARSRTX4gUcDdZEpqjqjMIuuCN3Eez825IuusOeH6RL5iut/DtDwB

before_build:
- dotnet restore

build_script:
- dotnet build --configuration Release /p:UnbreakablePolicyReportEnabled=false

test_script:
- .\test-all.bat
  
after_test:
- .\pack-all.bat

artifacts:
- path: '*.nupkg'

deploy:
  - provider: NuGet
    on:
      branch: /^master$/
    api_key:
      secure: aw9R6ewAkNjKU638SCzGho/fOwZCYecwb16d/cM923pCqb+bJztPsXEMYAdNx/vM
    artifact: /.*\.nupkg$/