version: '{build}'
configuration: Release

environment:
  api_key:
    secure: L9TTNCYYao5V7WxoXrRpjhf25X9o+yiQD1nTsOEXMFR24JQ20IKwrRoqNDFfV0oQ

before_build:
- dotnet restore

build_script:
- dotnet build --configuration Release /p:UnbreakablePolicyReportEnabled=false

test_script:
- .\test-all.bat
  
after_test:
- .\pack-all.bat

artifacts:
- path: '*.nupkg'

deploy_script:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe  
  - ps: $artifacts.values | ? { ($_.path -like '*.nupkg') -and  !($_.path -like '*.symbols.nupkg') } | % { nuget.exe push $_.path -Source https://www.nuget.org/api/v2/package -ApiKey $env:api_key }